name: Code Coverage

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  coverage:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Test coverage
        run: npm run coverage

      - uses: codecov/codecov-action@v1
        with:
          files: build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true
